#ifndef PROCESSING_H
#define PROCESSING_H

#pragma once

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A sRGB (?) color
typedef struct Color {
  float r;
  float g;
  float b;
  float a;
} Color;

// Initialize libProcessing.
//
// SAFETY:
// - This is called from the main thread if the platform requires it.
// - This can only be called once.
void processing_init(void);

// Create a WebGPU surface from a native window handle.
// Returns a window ID (entity ID) that should be used for subsequent operations.
// Returns 0 on failure.
//
// SAFETY:
// - Init has been called.
// - window_handle is a valid GLFW window pointer.
// - This is called from the same thread as init.
uint64_t processing_create_surface(uint64_t window_handle,
                                   uint32_t width,
                                   uint32_t height,
                                   float scale_factor);

// Destroy the surface associated with the given window ID.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_destroy_surface(uint64_t window_id);

// Update window size when resized.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_resize_surface(uint64_t window_id, uint32_t width, uint32_t height);

// Set the background color for the given window.
//
// SAFETY:
// - This is called from the same thread as init.
void processing_background_color(uint64_t window_id, struct Color color);

// Begins the draw for the given window.
//
// SAFETY:
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_begin_draw(uint64_t window_id);

// Flushes recorded draw commands for the given window.
//
// SAFETY:
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_flush(uint64_t window_id);

// Ends the draw for the given window and presents the frame.
//
// SAFETY:
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_end_draw(uint64_t window_id);

// Shuts down internal resources with given exit code, but does *not* terminate the process.
//
// SAFETY:
// - This is called from the same thread as init.
// - Caller ensures that update is never called again after exit.
void processing_exit(uint8_t exit_code);

// Set the fill color.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_set_fill(uint64_t window_id, float r, float g, float b, float a);

// Set the stroke color.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_set_stroke_color(uint64_t window_id, float r, float g, float b, float a);

// Set the stroke weight.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_set_stroke_weight(uint64_t window_id, float weight);

// Disable fill for subsequent shapes.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_no_fill(uint64_t window_id);

// Disable stroke for subsequent shapes.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_no_stroke(uint64_t window_id);

// Draw a rectangle.
//
// SAFETY:
// - Init and create_surface have been called.
// - window_id is a valid ID returned from create_surface.
// - This is called from the same thread as init.
void processing_rect(uint64_t window_id,
                     float x,
                     float y,
                     float w,
                     float h,
                     float tl,
                     float tr,
                     float br,
                     float bl);

// Check if the last operation resulted in an error. Returns a pointer to an error message, or null
// if there was no error.
const char *processing_check_error(void);

#endif  /* PROCESSING_H */
